version: "3.9"
services:
  api:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
  reverse-proxy:
    env_file: .env
    image: nginx:alpine
    ports:
      - target: 80
        published: $PUBLIC_API_PORT
        protocol: tcp
        mode: host
    volumes:
      - "./docker/nginx/:/etc/nginx/conf.d/"
    # using sh since this busybox doesn't have /bin/bash symlink
    command: sh -c "envsubst < /etc/nginx/conf.d/proxy.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  redis:
    image: redis:alpine
    volumes:
      - $DB_FILES_PATH/redis:/data
  mongo:
    image: mongo
    volumes:
      - $DB_FILES_PATH/mongo:/data/db
