name: flake8 lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2      
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
